[2025-07-05T11:56:26.039+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T11:56:26.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T11:56:21.697381+00:00 [queued]>
[2025-07-05T11:56:26.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T11:56:21.697381+00:00 [queued]>
[2025-07-05T11:56:26.056+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T11:56:26.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-07-05 11:56:21.697381+00:00
[2025-07-05T11:56:26.070+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T11:56:26.070+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T11:56:26.071+0000] {standard_task_runner.py:63} INFO - Started process 4486 to run task
[2025-07-05T11:56:26.073+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'extract', 'manual__2025-07-05T11:56:21.697381+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmppfv8kvny']
[2025-07-05T11:56:26.076+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask extract
[2025-07-05T11:56:26.112+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.extract manual__2025-07-05T11:56:21.697381+00:00 [running]> on host 6802b12b52ea
[2025-07-05T11:56:26.160+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T11:56:21.697381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T11:56:21.697381+00:00'
[2025-07-05T11:56:26.161+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T11:56:26.170+0000] {logging_mixin.py:188} INFO - [] файлы в папке
[2025-07-05T11:56:26.230+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T11:56:26.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T11:56:26.237+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=practice_etl_pipeline, task_id=extract, run_id=manual__2025-07-05T11:56:21.697381+00:00, execution_date=20250705T115621, start_date=20250705T115626, end_date=20250705T115626
[2025-07-05T11:56:26.285+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T11:56:26.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
