[2025-07-05T21:39:10.615+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T21:39:10.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:38:59.792230+00:00 [queued]>
[2025-07-05T21:39:10.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:38:59.792230+00:00 [queued]>
[2025-07-05T21:39:10.632+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T21:39:10.639+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_load> on 2025-07-05 21:38:59.792230+00:00
[2025-07-05T21:39:10.643+0000] {clientserver.py:570} INFO - Closing down clientserver connection
[2025-07-05T21:39:10.643+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=645) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-05T21:39:10.644+0000] {standard_task_runner.py:63} INFO - Started process 780 to run task
[2025-07-05T21:39:10.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'practice_etl_pipeline', 'transform_and_load', 'manual__2025-07-05T21:38:59.792230+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphp6xfo98']
[2025-07-05T21:39:10.647+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask transform_and_load
[2025-07-05T21:39:10.681+0000] {task_command.py:426} INFO - Running <TaskInstance: practice_etl_pipeline.transform_and_load manual__2025-07-05T21:38:59.792230+00:00 [running]> on host 93b0937d74ff
[2025-07-05T21:39:10.730+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='practice_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T21:38:59.792230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T21:38:59.792230+00:00'
[2025-07-05T21:39:10.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T21:39:11.998+0000] {logging_mixin.py:188} INFO - +----------+
|on_date   |
+----------+
|31.12.2017|
|31.12.2017|
|31.12.2017|
|31.12.2017|
|31.12.2017|
+----------+
only showing top 5 rows
[2025-07-05T21:39:12.229+0000] {logging_mixin.py:188} INFO - +----------+
|on_date   |
+----------+
|2017-12-31|
|2017-12-31|
|2017-12-31|
|2017-12-31|
|2017-12-31|
+----------+
only showing top 5 rows
[2025-07-05T21:39:12.396+0000] {logging_mixin.py:188} INFO - +----------+----------+-----------+-----------+
|on_date   |account_rk|currency_rk|balance_out|
+----------+----------+-----------+-----------+
|2017-12-31|14138     |44         |2.0003622E7|
|2017-12-31|34156756  |34         |99438.49   |
|2017-12-31|277937699 |34         |35341.17   |
|2017-12-31|13832     |34         |3951.94    |
|2017-12-31|20358     |34         |60328.29   |
|2017-12-31|23329     |21         |6245.06    |
|2017-12-31|17442     |34         |33245.41   |
|2017-12-31|16024     |34         |20673.34   |
|2017-12-31|40266     |34         |35664.89   |
|2017-12-31|13597     |35         |59604.09   |
|2017-12-31|13632     |44         |2.0082184E7|
|2017-12-31|24232     |44         |35263.28   |
|2017-12-31|17441     |34         |1072653.4  |
|2017-12-31|18006     |44         |80422.81   |
|2017-12-31|13843     |34         |17933.5    |
|2017-12-31|17436     |34         |5.0050756E7|
|2017-12-31|17434     |34         |5008134.0  |
|2017-12-31|24235     |35         |81577.79   |
|2017-12-31|24775     |34         |59326.31   |
|2017-12-31|306013958 |34         |63292.91   |
+----------+----------+-----------+-----------+
only showing top 20 rows
[2025-07-05T21:39:12.528+0000] {logging_mixin.py:188} INFO - +----------+----------+-----------+-----------+
|   on_date|account_rk|currency_rk|balance_out|
+----------+----------+-----------+-----------+
|2017-12-31|     14138|         44|2.0003622E7|
|2017-12-31|  34156756|         34|   99438.49|
|2017-12-31| 277937699|         34|   35341.17|
|2017-12-31|     13832|         34|    3951.94|
|2017-12-31|     20358|         34|   60328.29|
|2017-12-31|     23329|         21|    6245.06|
|2017-12-31|     17442|         34|   33245.41|
|2017-12-31|     16024|         34|   20673.34|
|2017-12-31|     40266|         34|   35664.89|
|2017-12-31|     13597|         35|   59604.09|
|2017-12-31|     13632|         44|2.0082184E7|
|2017-12-31|     24232|         44|   35263.28|
|2017-12-31|     17441|         34|  1072653.4|
|2017-12-31|     18006|         44|   80422.81|
|2017-12-31|     13843|         34|    17933.5|
|2017-12-31|     17436|         34|5.0050756E7|
|2017-12-31|     17434|         34|  5008134.0|
|2017-12-31|     24235|         35|   81577.79|
|2017-12-31|     24775|         34|   59326.31|
|2017-12-31| 306013958|         34|   63292.91|
+----------+----------+-----------+-----------+
only showing top 20 rows
[2025-07-05T21:39:16.870+0000] {logging_mixin.py:188} INFO - +----------+------+-------------------------------------------+-------+
|timestamp |status|message                                    |obj_num|
+----------+------+-------------------------------------------+-------+
|2025-07-05|ИНФО  |создана временная таблица temp_ft_balance_f|114    |
+----------+------+-------------------------------------------+-------+
[2025-07-05T21:39:17.258+0000] {logging_mixin.py:188} INFO - +----------+
|oper_date |
+----------+
|09-01-2018|
|09-01-2018|
|09-01-2018|
|09-01-2018|
|09-01-2018|
+----------+
only showing top 5 rows
[2025-07-05T21:39:17.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T21:39:17.526+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 220, in transform_and_load
    df = convert_date_columns(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 149, in convert_date_columns
    df.select(col_name).show(5, truncate=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/classic/dataframe.py", line 285, in show
    print(self._show_string(n, truncate, vertical))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/classic/dataframe.py", line 316, in _show_string
    return self._jdf.showString(n, int_truncate, vertical)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/spark-4.0.0-bin-hadoop3/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 288, in deco
    raise converted from None
pyspark.errors.exceptions.captured.DateTimeException: [CANNOT_PARSE_TIMESTAMP] Text '09-01-2018' could not be parsed at index 2. Use `try_to_date` to tolerate invalid input string and return NULL instead. SQLSTATE: 22007
[2025-07-05T21:39:17.537+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=practice_etl_pipeline, task_id=transform_and_load, run_id=manual__2025-07-05T21:38:59.792230+00:00, execution_date=20250705T213859, start_date=20250705T213910, end_date=20250705T213917
[2025-07-05T21:39:17.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 251 for task transform_and_load ([CANNOT_PARSE_TIMESTAMP] Text '09-01-2018' could not be parsed at index 2. Use `try_to_date` to tolerate invalid input string and return NULL instead. SQLSTATE: 22007; 780)
[2025-07-05T21:39:17.587+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T21:39:17.594+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T21:39:17.597+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
